# latexindentの設定ファイル
onlyOneBackUp: 1

defaultIndent: "  "

indentAfterHeadings:
  part:
    indentAfterThisHeading: 1
  chapter:
    indentAfterThisHeading: 1
  section:
    indentAfterThisHeading: 1
  subsection:
    indentAfterThisHeading: 1
  subsection*:
    indentAfterThisHeading: 1
  subsubsection:
    indentAfterThisHeading: 1
  paragraph:
    indentAfterThisHeading: 1
  subparagraph:
    indentAfterThisHeading: 1

indentAfterItems:
  itemize: 1
  enumerate: 1
  description: 1
  list: 1

indentRules:
  myenvironment: "  "
  anotherenvironment: "    "
  chapter: "  "
  section: "  "

replacements:
  - amalgamate: 1
  - # Insert 1 hlf-width space before and after "="
    substitution: s/(?<!\+|\-)\h{0,}\=\h{0,}(?!\+|\-)/ \= /g
    lookForThis: 1
  - # Insert half-width space before the "\" in any command
    substitution: s/\h{0,}\\(?!=\{)(\S)/ \\$2/g
    lookForThis: 0
  - # Combine 2 or more "half-width spaces" into 1
    substitution: s/\h+/ /g
    lookForThis: 1
    when: before
