name: make_pdf_in_tag

on:
  push:
    tags:
      - 'v*'  # タグのパターンを指定（ここでは "v" で始まるタグ）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t latex_docker .devcontainer/

    - name: Compile LaTeX document
      run: docker run --rm -v $PWD:/workdir latex_docker latexmk

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-document
        path: ./main.pdf

    - name: List files
      run: ls -R

    - name: Get Tag Name
      id: get_tag_name
      run: echo "::set-output name=tag::$(echo $GITHUB_REF | sed 's/refs\/tags\///')"

    - name: Generate PDF file name
      id: gen_pdf_name
      run: |
          TAG=$(echo ${{ steps.get_tag_name.outputs.tag }})
          PDF_NAME="HCI209_${TAG}.pdf"
          mv ./main.pdf ./$PDF_NAME
          echo "PDF_NAME=${PDF_NAME}" >> $GITHUB_ENV

    - name: List files after renaming
      run: ls -R

    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copy ./${{ env.PDF_NAME }} googledrive:/HCI209/
        id: upload_to_drive
